# TEST.yml
#   by Lut99
# 
# A Github action that automatically runs tests upon each new commit or pull request.

name: Continious integration
on:
  push:
    branches:
    - main
    - 'releases/**'
  pull_request:

jobs:
  test:
    name: Run Cargo tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
